DROP TABLE IF EXISTS "rolePermissions" CASCADE;
DROP TABLE IF EXISTS resources CASCADE;
DROP TABLE IF EXISTS modules CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS logs CASCADE;
DROP TABLE IF EXISTS users CASCADE;
